### ISSUE TITLE
People's bid

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#1012]
Chapter 6-3 should discuss the People's Bid for TikTok as an opportunity to implement the ideas in the (especially last two sections of the) chapter at a large scale.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 06-Sep-24 21:14:13 UTC` by Gov4Git `dev`

#### Notice `dl6clj`
Started managing this issue, using the Plural Management Protocol v1,  as Gov4Git concern `1012` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `t3eid5`
This issue's __priority score__ is now `0.000000`.
The __cost of priority__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `uybrfh`
The set of eligible proposals claiming this issue is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 08-Oct-24 14:09:27 UTC` by Gov4Git `dev`

#### Notice `4nxek6`
This issue was referenced by https://github.com/pluralitybook/plurality/pull/1024, managed as Gov4Git proposal `1024`.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 08-Oct-24 14:32:45 UTC` by Gov4Git `dev`

#### Notice `esqt2p`
This issue's __priority score__ is now `2500.000000`.
The __cost of priority__ is `2500.000000`.
The __projected bounty__ is now `2500.000000`.

#### Notice `d2yc7t`
The set of eligible proposals claiming this issue changed:
- https://github.com/pluralitybook/plurality/pull/1024, managed as Gov4Git motion `1024` with community attention of `0.000000`


#### Notice `wgpckl`
Freezing ❄️ this issue as there are eligible PRs addressing it:
- https://github.com/pluralitybook/plurality/pull/1024

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 22-Oct-24 19:57:48 UTC` by Gov4Git `dev`

#### Notice `iek3ra`
This issue, managed as Gov4Git concern `1012`, has been closed 🎉

The issue priority tally was `50.000000`.

Ths issue was resolved by [PR #1024](https://github.com/pluralitybook/plurality/pull/1024):

Tally breakdown by user:
- User @glenweyl contributed `50.000000` votes


#### Notice `vekxh4`
Gov4Git closed this issue, as the corresponding governance motion `1012` has now been closed.
