### ISSUE TITLE
Independent sources principle

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#1017]
A fundamental principle in journalism is the idea of two independent sources.  Many of the ideas in the book can be seen as enrichments and extensions of this.  Chapter 6-3 should refer to it therefore.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Saturday, 07-Sep-24 16:58:18 UTC` by Gov4Git `dev`

#### Notice `uyzwn5`
Started managing this issue, using the Plural Management Protocol v1,  as Gov4Git concern `1017` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `xmhz27`
This issue's __priority score__ is now `0.000000`.
The __cost of priority__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `3zpsso`
The set of eligible proposals claiming this issue is empty.

**Comment by SamRoizen** [comment]
Added information. PR #1042.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Saturday, 21-Dec-24 20:13:47 UTC` by Gov4Git `dev`

#### Notice `vaj4rq`
This issue, managed as Gov4Git concern `1017`, has been cancelled 🌂

The issue priority tally was `100.000000`.

Refunds issued:
- User @glenweyl was refunded `10000.000000` credits

Tally breakdown by user:
- User @glenweyl contributed `100.000000` votes
