### ISSUE TITLE
Improve contract law discussion

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#122]
The Contracts chapter discusses (briefly) contract law, incomplete contracts and the role of norms.  This discussion is roughly the right length and focus, but could be greatly improved by someone more knowledgeable about the area than.

**Comment by anoanoano** [comment]
I added / pull requested a few paragraphs on incomplete contracts and how they relate to the challenges with information sharing.

**Comment by pluralitybook** [comment]
These help, though I think there still might be a bit more of a legal theory perspective to be added (though might not be needed)

**Comment by anoanoano** [comment]
One relevant point: the legal-theoretical questions concerning incomplete contract, boundaries of the firm, and property / ownership rights blur together strongly. https://www.aeaweb.org/articles?id=10.1257/jep.25.2.181 A key point in that paper is that "ownership" of a firm refers to control of the residual rights attached to its assets, meaning the gaps or incompletenesses in the contracts otherwise governing the assets. So, through the lens of incomplete contract, you can see the meaning of firm ownership and you can also see the boundaries of the firm. Conversely through a theory of the firm, or a theory of property, you can see the meaning of incomplete contract.

The firm is the total power afforded by the assets of the firm, minus what others have contractual or other legal claims to. The owners are whoever can exercise that uncontracted power. Replace "firm" with "property" in that last sentence and it also works.

Thus "the firm" is not the contracts comprising it, but the power in the negative space left by the contracts. If developed, this line of thought could also clearly illustrate the difference between a "firm" and an "association." (The owners of a firm have a common interest, like much like an association. But that common interest is peculiar -- it is "increasing their power" eg via market value. (Aside: I think it is easy and kind of dangerous to say this is an oversimplification -- it's truly not that much of an oversimplification, especially wrt passive shareholders.) However, as you correctly say in the associations chapter: "associations must be able to protect themselves from surveillance, as if their common beliefs become simply the beliefs of everyone, they cease to be a separate association." The common interest of firm owners in increasing their power is therefore a defective ground of association in two ways. First, it is not secret. Everyone knows what Amazon shareholders have in common: a desire for the number on the ticker to increase. Second, it is not unique -- it is "simply the beliefs of everyone" that having more money would be nice. This is why typical firms (as collections of owners, less so as collections of employees, which would require a different analysis) are sort of "false" or defective associations.)

LMK if you'd like me to weave some of this in here or elsewhere.

**Comment by anoanoano** [comment]
Another legal theory thing that might be worth a passing mention in this context is the Hohfeldian incidents
