### ISSUE TITLE
Add links throughout the book so that the digital version is more hypertextual

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#159]

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 01-Mar-24 01:25:03 UTC` by Gov4Git `dev`

#### Notice `lj3mh4`
Started managing this issue as Gov4Git concern `159` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `bcp2ma`
This issue's __priority score__ is now `0.000000`.
The __cost of priority__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `gdl6f3`
The set of eligible proposals claiming this issue is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 01-Mar-24 20:45:01 UTC` by Gov4Git `dev`

#### Notice `pp6v64`
This issue's __priority score__ is now `999.000000`.
The __cost of priority__ is `998001.000000`.
The __projected bounty__ is now `1998.000000`.

#### Notice `to55dj`
The set of eligible proposals claiming this issue is empty.

**Comment by nishio** [comment]
In Japanese forum, we are achieving the same goal like this:

<img width="1265" alt="image" src="https://github.com/pluralitybook/plurality/assets/315198/e007ddb3-b90d-475c-86b4-5c355d4880b2">
<img width="1120" alt="image" src="https://github.com/pluralitybook/plurality/assets/315198/732f7898-8367-49b4-98f4-4b6e6c8d31b3">

I chose Scrapbox, real-time collaborative editing wiki system, for our purpose. However, it may not fit to the pluralitybook purpose, because in pluralitybook we want to put the source on github as markdown, not on a proprietary service. Quartz is possible OSS solution.

https://quartz.jzhao.xyz/

**Comment by nishio** [comment]
I've written several books and conducted an experiment by placing one of them in my Scrapbox. From this experience, I'd like to share my insights.

The majority of readers, who are accustomed to the legacy format of books, prefer content arranged in a linear fashion. They prefer knowing what they should read next, rather than being forced to make decisions about which link to follow.

On the other hand, there is a small but significant number of people, myself included, who prefer knowledge organized in a networked manner. These individuals prefer reading Wikipedia and, before Wikipedia existed, enjoyed reading dictionaries.

It's challenging to meet both of these needs with a single source. To effectively shape a network of knowledge, book sections are often too lengthy. My suggestion is to fork the one-dimensional manuscript intended for books after it's finalized, and then further divide it to create the data for a Wiki. I can help it.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Saturday, 02-Mar-24 14:23:28 UTC` by Gov4Git `dev`

#### Notice `xv7pn5`
This issue's __priority score__ is now `1009.000000`.
The __cost of priority__ is `998101.000000`.
The __projected bounty__ is now `2018.000000`.

#### Notice `njhajp`
The set of eligible proposals claiming this issue is empty.

**Comment by nishio** [comment]
Further discussion from [Discord](https://discord.com/channels/1133444567031627846/1142730717739089982/1213312751984836700)

nishio — 03/02/2024 11:31 AM
>I have also put in a bunch of matching funds and direct prioritization to help give you a sense of the issues that need your most urgent attention.

However, while the top issue Add links throughout the book so that the digital version is more hypertextual is important, because it's geared towards the digital environment, its urgency seems lower compared to activities for printed books...
Maybe the current best way to take attention to the urgent issues is to post in announcements channel (so I avoided to reply this random thought in the announcement channel) 

GlenWeyl
I will do that as well...but the links thing is in my view not that divorcable from the footnotes...you can basically do them at the same time.  But I agree with your point

nishio
I may have misunderstood your intention. Were you perhaps referring to external links (such as to Wikipedia) from the manuscript? I was thinking about internal links between concepts within the manuscript.

GlenWeyl
I was mostly talking about external links
Internal links can definitely come later
Also not just Wikipedia...more than anyting we want to point to projects and ideas that are allied and we hope people read about

**Comment by nishio** [comment]
The Japanese translation community has included numerous external links in Japanese version to deepen collective understanding. I'm going to encourage community members to reflect that information in the English version.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Wednesday, 06-Mar-24 20:46:24 UTC` by Gov4Git `dev`

#### Notice `nsjm77`
This issue's __priority score__ is now `1014.000000`.
The __cost of priority__ is `998126.000000`.
The __projected bounty__ is now `2028.000000`.

#### Notice `pe2wpt`
The set of eligible proposals claiming this issue is empty.

**Comment by wesc** [comment]
What is the thinking on when to link directly from text to a site vs. a footnote citation? A few thoughts:

- Footnotes will work better in print. Can the print scripts automatically translate an external link to a footnote?
- Most printed material has an online home, such as arxiv
- Many classic texts have pdf excerpts online. Is it appropriate to link to these?

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Monday, 18-Mar-24 02:35:21 UTC` by Gov4Git `dev`

#### Notice `cquwqt`
This issue's __priority score__ is now `1034.000000`.
The __cost of priority__ is `998526.000000`.
The __projected bounty__ is now `2068.000000`.

#### Notice `qxidk2`
The set of eligible proposals claiming this issue is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Monday, 18-Mar-24 02:47:02 UTC` by Gov4Git `dev`

#### Notice `hrcu35`
This issue's __priority score__ is now `1034.000000`.
The __cost of priority__ is `998526.000000`.
The __projected bounty__ is now `2068.000000`.

#### Notice `or5fah`
The set of eligible proposals claiming this issue is empty.

**Comment by GlenWeyl** [comment]
@wesc you can see how I've been doing it...I do some of both and often both cite and link, so that it will show up well in both formats, but some things are not really useful as cites (e.g. websites) and some things are not really useful as links (e.g. references to academic material archived behind a paywall).

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 19-Mar-24 18:31:00 UTC` by Gov4Git `dev`

#### Notice `7gvlou`
This issue, managed as Gov4Git proposal `159`, has been cancelled 🌂

The __priority score__ of the issue was `1034.000000`.
The __cost of priority__ of the issue was `998526.000000`.

Refunds issued:
- User @glenweyl was refunded `998001.000000` credits
- User @jason-entenmann was refunded `25.000000` credits
- User @lauerj was refunded `100.000000` credits
- User @shaudub was refunded `400.000000` credits

Tally breakdown by user:
- User @jason-entenmann contributed `5.000000` votes
- User @lauerj contributed `10.000000` votes
- User @shaudub contributed `20.000000` votes
- User @glenweyl contributed `999.000000` votes
