### ISSUE TITLE
Add links to and improve discussion of representation of non-human entities in Deliberation section

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#167]

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 01-Mar-24 17:01:41 UTC` by Gov4Git `dev`

#### Notice `i7kgsl`
Started managing this issue as Gov4Git concern `167` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `7fehah`
This issue's __priority score__ is now `0.000000`.
The __cost of priority__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `27fn6l`
The set of eligible proposals claiming this issue is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 01-Mar-24 20:45:02 UTC` by Gov4Git `dev`

#### Notice `h54vxd`
This issue's __priority score__ is now `100.000000`.
The __cost of priority__ is `100.000000`.
The __projected bounty__ is now `100.000000`.

#### Notice `urbxd6`
The set of eligible proposals claiming this issue is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 19-Mar-24 18:31:01 UTC` by Gov4Git `dev`

#### Notice `bj63di`
This issue, managed as Gov4Git concern `167`, has been cancelled 🌂

The issue priority tally was `10.000000`.

Refunds issued:
- User @glenweyl was refunded `100.000000` credits

Tally breakdown by user:
- User @glenweyl contributed `10.000000` votes
