### ISSUE TITLE
Add discussion of comparative advantage as an example of harnessing diversity to "Collaborative Tech" and/or "Markets" chapter

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#175]

**Comment by lauerj** [comment]
This is a really nice thought - I will think whether I have a strategy to develop a PR on this issue. Might link well with pooling and public goods (and thge principal-agency workaround)

**Comment by GlenWeyl** [comment]
Have you read my work with Veiga and Mahoney?  Pooling is a very broad issue


___________________________________________________
Research Lead, Plural Technology Collaboratory (https://aka.ms/plural), Research Special Projects
___________________________________________________
Outside of Microsoft I am Founder of RadicalxChange (https://radicalxchange.org) and Founder and Chair of the Plurality Institute (https://plurality.institute)
________________________________

**Comment by lauerj** [comment]
I'd seen the work on adverse selection and market power. Are you referring to multidimensional platform design? Or competition policy and product design? Or pricing institutions and adverse selection? All of the above? Platform design seems immediately relevant to the concerns I had in mind and is very plurality friendly. The original post issue of comparative advantage (CA) is interesting as a kind of perpetual motion machine for harnessing diversity in productive efficiency - not sure how much the pooling discussion reads across to the OP concerns, but binary models such as CA and principal-agency (PA) seem like proto-pooling models. There's possibly an analogy btw PA and CA, where PA is the informational version, and non-binary models (e.g. multidimensional markets) can yield additional welfare gains.

**Comment by lauerj** [comment]
BTW in the section on health insurance that I rewrote significantly after your previous comments on the pre-github markdown version, some of these issues come up: competition policy, adverse selection, network (i.e. 'platform') goods and plural goods etc. Sot it's almost like I had read those papers.

**Comment by GlenWeyl** [comment]
This is a longer conversation than I have the bandwidth to have in this forum during this crunch but if you think there is something you want to add before printing, I can try to make time to discuss live.


___________________________________________________
Research Lead, Plural Technology Collaboratory (https://aka.ms/plural), Research Special Projects
___________________________________________________
Outside of Microsoft I am Founder of RadicalxChange (https://radicalxchange.org) and Founder and Chair of the Plurality Institute (https://plurality.institute)
________________________________

**Comment by lauerj** [comment]
Let me draft something first, send it to you, and then we can discuss live. So we will have that live conversation iff there is a PR to resolve this issue, otherwise it can stay open.

**Comment by GlenWeyl** [comment]
Perfect!


___________________________________________________
Research Lead, Plural Technology Collaboratory (https://aka.ms/plural), Research Special Projects
___________________________________________________
Outside of Microsoft I am Founder of RadicalxChange (https://radicalxchange.org) and Founder and Chair of the Plurality Institute (https://plurality.institute)
________________________________

**Comment by lauerj** [comment]
hi Glen,
Here's some text as promised. I would suggest putting it at line 64 of
05-00 (at the end of *Collaboration Across Diversity* and just before *The
Depth Breadth Spectrum*), but that may require more thought.
Please let me know if you'd like to discuss this further, or if you'd like
me to make a PR in response to this issue (which would also close out the
issue I raised about principal-agency).
Best, Jeremy

    As the low-entropy examples suggest, pooling across differences as a
source of benefit is a very general principle.  Since pooling works by
aggregation, it faces a problem not unlike that for the production of
public goods, which is how to attract the right number of users/producers
for the benefit to emerge.  Indeed there are some canonical economic and
social relations that might be called ‘proto-public goods' since they work
through a reduced form of pooling entailing certain equally canonical
disadvantages.  For example, the principle of comparative advantage means
that only when parties specialize in the production of the good they make
best is aggregate welfare maximized under trade, which can result in
over-exploitation and fragility at a macro-scale.  At the micro-level,
principal-agency arises from asymmetric information between parties driven
by an almost mechanical logic to exploit their differences through trade: I
may know better than anyone how I feel, but only my doctor may know for
sure whether my heart is weak, and paternalism thus casts its long
shadow.  A pooling-of-difference logic also applies to multi-sided markets
where there are distinct groups of customers who are more valuable to serve
together or to selection markets where customers have varying costs of
service. The specific strategy to maximize benefit differs, but the general
principle is that, although size matters, bigger is not always better: what
can matter more in fact is the strength of connections, where, for example,
families, teams or troops – small networks completely connected by
high-value interactions – can outperform in the production of key plural
goods much larger ones with lower measures of centrality.  Trade is
ancient, and banding together to perform key social functions even more so
if we consider the record of Paleolithic art. Pooling of difference at
diverse scales, but by non-state actors, would thus seem to be an exception
to the rule that 'public goods' are always under-supplied.

**Comment by GlenWeyl** [comment]
Jeremy,
I don’t support getting into this at this level of abstraction.  If this material belongs somewhere it’s in 05-07 on markets.  This is just not fundamental enough to go in the information theoretic foundation of this all.

Glen


___________________________________________________
Research Lead, Plural Technology Collaboratory (https://aka.ms/plural), Research Special Projects
___________________________________________________
Outside of Microsoft I am Founder of RadicalxChange (https://radicalxchange.org) and Founder and Chair of the Plurality Institute (https://plurality.institute)
________________________________

**Comment by lauerj** [comment]
hi Glen, Personally, I wouldn't push this to anywhere in 05-07 as the flow
there doesn't have hooks for it. We both think these issues are relevant,
but where requires more thought. As I don't think there's anything
fundamental that will be missed by rejecting, happy to shelve for now.
Best, Jeremy

**Comment by GlenWeyl** [comment]
You could put a footnote somewhere of pooling as an example of collaboration.


___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects

___________________________________________________

Collaborate<https://github.com/pluralitybook/plurality> with Digital Minister Audrey Tang, myself and dozens around the world to tell the story of Plurality<https://www.plurality.net/>



________________________________

**Comment by lauerj** [comment]
Good suggestion. I've added a footnote (text below) to the penultimate
paragraph of 05-07 in my fork, and will include it in my next PR (the rest
of which is copy-edits of 06-03 and the fixing of references in 06-03).
Comments welcome.

   Pooling across diversity is a very general principle.  Although size
matters, bigger is not always better, and the strength of connections can
matter more. For example, families, teams or troops – small networks
connected by high-value interactions – can outperform much larger ones in
the production of ⿻ goods.  If we consider the record of Paleolithic art,
banding together to perform key social functions is extremely ancient, so
collaborative pooling at diverse scales, albeit by non-state and non-market
actors, seems an exception to the rule that 'public goods' are always
under-supplied.

**Comment by GlenWeyl** [comment]
@lauerj it would be great if you want to directly address the point of this issue.  I am funding it now.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Sunday, 10-Mar-24 21:21:15 UTC` by Gov4Git `dev`

#### Notice `an47br`
Started managing this issue, using the Plural Management Protocol v1,  as Gov4Git concern `175` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `ymdqur`
This issue's __priority score__ is now `0.000000`.
The __cost of priority__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `7mictm`
The set of eligible proposals claiming this issue is empty.

**Comment by lauerj** [comment]
ok thanks will take a crack, welcome other inputs if any

**Comment by GlenWeyl** [comment]
This is pretty simple...the idea is just to say "comparative advantage is precisely the idea of gains from diversity through the market mechanism, but of course this is just one manifestation of that idea and misses many other richer versions, as highlighted by later trade theory that is more sophisticated about supermodularity", but without assuming prior knowledge of the idea of comparative advantage.

________________________________

**Comment by lauerj** [comment]
Yes, thank you, I see that and can definitely provide some text for review later today (GMT).

**Comment by lauerj** [comment]
Thanks, @GlenWeyl. I've made a PR for this issue:
- it seemed easier to add the text on this issue to 05-00 where there is an explicit discussion of the benefits from diversity.
- there does not seem to be a non-zero bounty associated with this issue, i.e. the bounty is zero (which is fine btw).
- let me know if you prefer a different approach or want any changes that it would be too time-consuming for you to make directly.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Sunday, 28-Apr-24 19:32:04 UTC` by Gov4Git `dev`

#### Notice `xw4w3k`
This issue, managed as Gov4Git concern `175`, has been cancelled 🌂

The issue priority tally was `0.000000`.

Refunds issued:

Tally breakdown by user:
