### ISSUE TITLE
Add chart of ChatGPT adoption to "From Plurality to Reality" chapter

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#205]

**Comment by GregCTWang** [comment]
There are graphs illustrating the "Time taken to reach 1 million users," which include comparisons with other apps/services (for example, [this graph](https://miro.medium.com/v2/resize:fit:1400/0*bZxY-YzCbFQZO9XS.jpg)) or focus specifically on growth rates (for example, [this analysis](https://www.similarweb.com/blog/insights/ai-news/chatgpt-25-million/#:~:text=Just%20this%20week%2C%20a%20UBS,Reuters%20and%20widely%20quoted%20elsewhere.)). Since we mentioned that "ChatGPT achieved 100 million users within a few months of its launch," perhaps the direction of the second example might resonate more with our audience. However, we'll need to source official data for this; I've only found press articles that don't provide data sources.

**Comment by GregCTWang** [comment]
@ccerv1 What's your thought on this issue?

**Comment by ccerv1** [comment]
> @ccerv1 What's your thought on this issue?

I'd like to offer a third example, which is a based off of the first but looks at improvements in [sprint times](![image](https://github.com/pluralitybook/plurality/assets/42869436/1207b185-af3a-4a3f-b63e-5ec9a39553c1)) among runners:

![image](https://github.com/pluralitybook/plurality/assets/42869436/31bb495e-523e-4308-9f78-b43123fb34be)

**Comment by GlenWeyl** [comment]
I love this idea!

**Comment by GregCTWang** [comment]
@ccerv1 I agree with your view on the netscribes data viz, shall we use their data points and create a new figure? I double-checked the source.

**Comment by GregCTWang** [comment]
@ccerv1 Happy to help out with more data or support on this!

**Comment by ccerv1** [comment]
Just made the chart!
![chatgpt_adoption](https://github.com/pluralitybook/plurality/assets/42869436/3ae3e15d-7cf6-45af-ad55-68d53c578927)

**Comment by GlenWeyl** [comment]
Love it!  Just add.
