### ISSUE TITLE
Improve citations of economics of agglomeration literature in "Workplace" chapter

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#215]

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 01-Mar-24 17:01:44 UTC` by Gov4Git `dev`

#### Notice `ehsnro`
Started managing this issue as Gov4Git concern `215` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `6il66k`
This issue's __priority score__ is now `0.000000`.
The __cost of priority__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `o7nige`
The set of eligible proposals claiming this issue is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 01-Mar-24 21:15:47 UTC` by Gov4Git `dev`

#### Notice `ll6jdp`
This issue's __priority score__ is now `3600.000000`.
The __cost of priority__ is `3600.000000`.
The __projected bounty__ is now `3600.000000`.

#### Notice `3n2xro`
The set of eligible proposals claiming this issue is empty.

**Comment by GregCTWang** [comment]
Economics of agglomeration literature:

- Rosenthal, Stuart S. and William Chal Strange. “Evidence on the nature and sources of agglomeration economies.” Handbook of Regional and Urban Economics 4 (2004): 2119-2171.
https://www.semanticscholar.org/paper/Evidence-on-the-nature-and-sources-of-agglomeration-Rosenthal-Strange/4c71d1fa5d1c4cae618f16703bbddb55d9b5cf69

- Fujita, Masahisa and Jacques-François Thisse. “Economics of Agglomeration: Cities, Industrial Location, and Regional Growth.” (2002). 
https://www.semanticscholar.org/paper/Economics-of-Agglomeration%3A-Cities%2C-Industrial-and-Fujita-Thisse/df035e8dbba4119db1b8c7a8047bff14b3669653

- Fujita, Masahisa and Jacques-François Thisse. “The Economics of Agglomeration.” Oxford Research Encyclopedia of Economics and Finance (1996): n. pag.
https://www.semanticscholar.org/paper/The-Economics-of-Agglomeration-Fujita-Thisse/15f09ab34d264e36d29897af6fbbff71505652f3

**Comment by GregCTWang** [comment]
Footnote [1] links properly cited:

Greenstone, Michael, Richard Hornbeck, and Enrico Moretti. “Identifying Agglomeration Spillovers: Evidence from Winners and Losers of Large Plant Openings.” Journal of Political Economy 118, no. 3 (June 2010): 536–98. https://doi.org/10.1086/653714.

Klein, Cameron, Deborah DiazGranados, Eduardo Salas, Huy Le, C. Shawn Burke, Rebecca Lyons, and Gerald F. Goodwin. “Does Team Building Work?” Small Group Research 40, no. 2 (January 16, 2009): 181–222. https://doi.org/10.1177/1046496408328821.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Saturday, 02-Mar-24 18:40:18 UTC` by Gov4Git `dev`

#### Notice `nc5fju`
This issue, managed as Gov4Git concern `215`, has been cancelled 🌂

The issue priority tally was `60.000000`.

Refunds issued:
- User @glenweyl was refunded `3600.000000` credits

Tally breakdown by user:
- User @glenweyl contributed `60.000000` votes
