### ISSUE TITLE
Add evidence and citations on the "false consensus" and "pluralistic ignorance" effects and their consequences to the "Media" chapter

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#221]

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 01-Mar-24 20:45:05 UTC` by Gov4Git `dev`

#### Notice `wbecc4`
This issue's __priority score__ is now `30625.000000`.
The __cost of priority__ is `30625.000000`.
The __projected bounty__ is now `30625.000000`.

#### Notice `tel5mm`
The set of eligible proposals claiming this issue is empty.

**Comment by lauerj** [comment]
@GlenWeyl I could make some light additions on COVID conspiracies, e.g.:
- vaccine 'hesitancy' and worse
- disputes about zoonotic origins
- on another topic, one could also mention J6 attack on Capitol Hill in this context.

**Comment by GlenWeyl** [comment]
Sure!


___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects

___________________________________________________

Collaborate<https://github.com/pluralitybook/plurality> with Digital Minister Audrey Tang, myself and dozens around the world to tell the story of Plurality<https://www.plurality.net/>



________________________________

**Comment by lauerj** [comment]
I've added a footnote as anything longer than that will require more extensive revisions that are permitted at this stage.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 12-Mar-24 09:32:14 UTC` by Gov4Git `dev`

#### Notice `ypajyk`
This issue, managed as Gov4Git concern `221`, has been cancelled 🌂

The issue priority tally was `175.000000`.

Refunds issued:
- User @glenweyl was refunded `30625.000000` credits

Tally breakdown by user:
- User @glenweyl contributed `175.000000` votes
