### ISSUE TITLE
Why "on a blockchain" 

### ISSUE THREAD

**Issue by Identitywoman** [pluralitybook/plurality#240]
https://github.com/pluralitybook/plurality/blob/493c1aae9183eb51fa9840b43502b35d52211dc2/contents/english/04-01-identity-and-personhood.md?plain=1#L18

I thought I would raise this issue publicly - just so it can be transparently seen. 
I think people asserting this type of information "on a blockchain" where the information is actually embedded in it - and publicly visible is a problematic architecture - particularly for vulnerable folks.  Even if it is "positive" and "she consented" to the public assertions. 
Maybe this is not what you were imagining - maybe she is sharing Verifiable Credentials that are "backed by a public keys stored on a blockchain and embedded in a governance framework to know who made the assertions" 

This use-case also is skipping over a critical issue - which is how can you "believe" (trust) the assertion by the entities making positive statements - how do you know they make accurate true statements - these governance problems are actually where things become "real" in all identity systems (formal "government issued" ones or the type you are describing)

**Comment by GlenWeyl** [comment]
This story was written by @noahda0. I don't disagree with your critiques here, but I also don't feel as strongly about them as you do @Identitywoman.  I'd suggest you two work through it and find something that you think works for everyone.  Currently Taiwan is planning to use a DID-VC framework that includes some blockchain elements and @noahda0 is doing the primary envisioning work for this.

**Comment by noahda0** [comment]
Hi @Identitywoman Kaliya, thanks a lot for the feedback, we met a while ago in a call with DML, I had a great time listening to your thoughts.

on blockchain > I understand most DID solutions including VC and narratives from Open ID foundations don’t mention blockchain that much, but in certain cases blockchain might still be useful, I’m imagining some govern on-chain data off-chain scenarios or credentials that should not be open to revocation by any issuer. However I’m not insistent on this, being on blockchain is just one possibility which I believe do provide more resilience, but I also understand many credentials, VCs might not.

on the assertions > I think in this story the government official would have a list of DID addresses on hand which they believe to be trustworthy, and the verification machine would only recognize credentials signed by the believable organizations or individuals, I simply didn’t put it in there because the purpose of the story is not to persuade readers on the technical details but to illustrate how it might look like in the future.

These are just some quick thoughts, I’m happy to make any further changes necessary, let me know what you think.

**Comment by Identitywoman** [comment]
@noahda0 Thanks for sharing your thoughts. Maybe we can have a quick call to talk through things. 

The VC use-cases generally don't mention blockchain in part because they are entirely off-chain artifacts.  The defacto type of or easiest way to make a VC is to not make it revokable.  To make a VC revokable requires the Issuer to make a revocation system and list that they post to regularly.  

There is a bunch of work going on to develop tools and systems for developing trust registries - lists of issuers of various types.

This is from the Trust over IP Foundation Trust Registry specificaiton
_"The purpose of this ToIP specification is to define a standard interoperable protocol for interacting with a global web of peer trust registries, each of which can answer queries about whether a particular party is trusted and authorized to perform a particular action in a particular digital trust ecosystem, as well as which peer trust registries trust each other."_ 

Then there is another layer if you have a registry for a particular thing - say the universities in a given country that issue degrees. How do you find the registries of other countries. 

This is where the directories of registries come in my colleague Lucy is working directly on this and it an open source project within UNDP- https://github.com/undp/Regi-TRUST

The approach you are suggesting is a allow (white) list approach which can "work" but it is not globally scalable.

**Comment by noahda0** [comment]
@Identitywoman I would love to jump on a call.

Yes I fully agree with you on the VC revocation structure, we simply saw most VC/DID systems built today gave issuers the ability for revocation, one reason being most of these systems are being initiated by governments (US Taiwan both), also the reason can also be practical, membership issuance without revocations can be problematic for businesses and governments, and that's why I think the issuer revocation systems would continue to exist.

But like I said, I'm happy to take out the on blockchain part, that part can certainly go either way. I'll do that in the next couple of days.

I would love to chat with Lucy too, we are in the process of designing a registry, would love to pick her brain about this too.

**Comment by Identitywoman** [comment]
Lets find a time to talk? can you e-mail me? kaliya@identitywoman.net

I wrote this in a different issue earlier: 

> This young woman is a leader in a war torn village/country. Information about her activities locally that is documented on a ledger that is public could create significant risk to her. Why is this the strategy to support information sharing about her good works. If the EU recognizes an organization, and this organization is registered in a governance or trust registry (this can be on a blockchain) - and in that registry is the public keys that are associated with private keys they would use to sign a statement - could they not sign a verifiable credential - that is under her control? This is a much less risky way of supporting her having information about her activities then putting this on a ledger that entities who might want to bring harm to her - like killing all the good leaders in her village also having access to the information.


I do think we need to figure out how to support this woman and how we leverage blockchains and data structures that are outside of the control of a "central state" or a "big tech company" that can erase them.   Would be great to align on how to improve this story and help set a good example for how to do this without potentially putting our subject in danger.

**Comment by Identitywoman** [comment]
This was resolved by pull request 
https://github.com/pluralitybook/plurality/pull/521
