### ISSUE TITLE
Ensure consistency of formatting, indentation etc. throughtout book.

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#26]

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Thursday, 29-Feb-24 21:23:20 UTC` by Gov4Git `dev`

#### Notice `kn6eyn`
Started managing this issue as Gov4Git concern `26` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `476yh6`
This issue's __priority score__ is now `0.000000`.
The __cost of priority__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `qx3uyp`
The set of eligible proposals claiming this issue is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 01-Mar-24 20:45:06 UTC` by Gov4Git `dev`

#### Notice `etsnp7`
This issue's __priority score__ is now `300.000000`.
The __cost of priority__ is `90000.000000`.
The __projected bounty__ is now `600.000000`.

#### Notice `mmfbqu`
The set of eligible proposals claiming this issue is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 19-Mar-24 18:31:05 UTC` by Gov4Git `dev`

#### Notice `sl6fhb`
This issue, managed as Gov4Git proposal `26`, has been cancelled 🌂

The __priority score__ of the issue was `310.000000`.
The __cost of priority__ of the issue was `90100.000000`.

Refunds issued:
- User @glenweyl was refunded `90000.000000` credits
- User @jason-entenmann was refunded `100.000000` credits

Tally breakdown by user:
- User @glenweyl contributed `300.000000` votes
- User @jason-entenmann contributed `10.000000` votes
