### ISSUE TITLE
Issuing credits to Audrey

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#339]
Issue 12625000 credits to @audreyt .

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Tuesday, 27-Feb-24 22:19:18 UTC` by Gov4Git `dev`

Could not issue `1.2625e+07` credits to member @audreyt. Reopen the issue to retry.

Because: `file does not exist`
