### ISSUE TITLE
Issuing credits to Aki

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#342]
Issue 1493521 credits to @akinorioyama.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Tuesday, 27-Feb-24 22:19:15 UTC` by Gov4Git `dev`

Could not issue `1.493521e+06` credits to member @akinorioyama. Reopen the issue to retry.

Because: `file does not exist`
