### ISSUE TITLE
Issuing credits to Judith

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#346]
Issue 1000000 credits to @jdthamores.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Tuesday, 27-Feb-24 22:19:11 UTC` by Gov4Git `dev`

Could not issue `1e+06` credits to member @jdthamores. Reopen the issue to retry.

Because: `file does not exist`
