### ISSUE TITLE
Issuing credits to Nick

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#350]
Issue 598154 credits to @npyati .

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Tuesday, 27-Feb-24 22:19:07 UTC` by Gov4Git `dev`

Could not issue `598154` credits to member @npyati. Reopen the issue to retry.

Because: `file does not exist`
