### ISSUE TITLE
Issuing credits to Mat

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#354]
Issue 250000 credits to @matdryhurst.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Tuesday, 27-Feb-24 22:41:45 UTC` by Gov4Git `dev`

Could not issue `250000` credits to member @matdryhurst. Reopen the issue to retry.

Because: `file does not exist`
