### ISSUE TITLE
Deepen discussion of diversity of historical property institutions in The Lost Dao

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#36]
The Property section of The Lost Dao chapter discusses the historical idiosyncracy of Western industrial property relations.  This could use another paragraph of depth, citations and examples.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 12-Jan-24 22:29:02 UTC` by Gov4Git `dev`

### Notice `prlnpg`
Started managing this issue as Gov4Git concern `36` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 01-Mar-24 20:45:10 UTC` by Gov4Git `dev`

#### Notice `lrogg6`
This issue's __priority score__ is now `200.000000`.
The __cost of priority__ is `40000.000000`.
The __projected bounty__ is now `40000.000000`.

#### Notice `jxtwjm`
The set of eligible proposals claiming this issue is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Sunday, 10-Mar-24 21:27:22 UTC` by Gov4Git `dev`

#### Notice `253ryn`
This issue, managed as Gov4Git concern `36`, has been cancelled 🌂

The issue priority tally was `200.000000`.

Refunds issued:
- User @glenweyl was refunded `40000.000000` credits

Tally breakdown by user:
- User @glenweyl contributed `200.000000` votes
