### ISSUE TITLE
Issuing credits to Jordan

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#364]
Issue 76471 credits to @Jordanu12.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 28-Feb-24 17:40:38 UTC` by Gov4Git `dev`

Could not issue `76471` credits to member @jordanu12. Reopen the issue to retry.

Because: `file does not exist`
