### ISSUE TITLE
Issuing credits to Kevin

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#372]
Issue 5000 credits to @owocki.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 28-Feb-24 17:52:22 UTC` by Gov4Git `dev`

Could not issue `5000` credits to member @owocki. Reopen the issue to retry.

Because: `file does not exist`
