### ISSUE TITLE
Deepen discussion of diversity of historical voting institutions in The Lost Dao chapter

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#38]
The Lost Dao chapter contains a discussion of how modern Western liberal democracies have flattened the historical diversity of voting and collective decision-making institutions.  This deserves 1-2 more paragraphs of depth, examples and citations; I am particularly in including references to relatively recent divergences, such as consociationalism and functional representation.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Thursday, 29-Feb-24 21:35:45 UTC` by Gov4Git `dev`

#### Notice `muk76d`
Started managing this issue as Gov4Git concern `38` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `t6ylf2`
This issue's __priority score__ is now `0.000000`.
The __cost of priority__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `jkrzrp`
The set of eligible proposals claiming this issue is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 01-Mar-24 20:45:11 UTC` by Gov4Git `dev`

#### Notice `i67ajm`
This issue's __priority score__ is now `200.000000`.
The __cost of priority__ is `40000.000000`.
The __projected bounty__ is now `400.000000`.

#### Notice `63agrx`
The set of eligible proposals claiming this issue is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Sunday, 10-Mar-24 21:21:19 UTC` by Gov4Git `dev`

#### Notice `bd7iss`
This issue, managed as Gov4Git proposal `38`, has been cancelled 🌂

The __priority score__ of the issue was `200.000000`.
The __cost of priority__ of the issue was `40000.000000`.

Refunds issued:
- User @glenweyl was refunded `40000.000000` credits

Tally breakdown by user:
- User @glenweyl contributed `200.000000` votes
