### ISSUE TITLE
Add a footnote on Max Weber to The Lost Dao

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#39]
Add a footnote to The Lost Dao section on "The Limits of Modernity" highlighting Max Weber's work as the codification of the nature of the modern state.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 12-Jan-24 22:29:02 UTC` by Gov4Git `dev`

### Notice `mh43na`
Started managing this issue as Gov4Git concern `39` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 01-Mar-24 20:45:12 UTC` by Gov4Git `dev`

#### Notice `3toomb`
This issue's __priority score__ is now `10.000000`.
The __cost of priority__ is `100.000000`.
The __projected bounty__ is now `100.000000`.

#### Notice `qaheby`
The set of eligible proposals claiming this issue is empty.

**Comment by 41hulk** [comment]
@GlenWeyl  seems like that section isn't in the The Lost Dao chapter. kindly help

**Comment by GlenWeyl** [comment]
It is now Connected Society.

**Comment by 41hulk** [comment]
Great, Found it

**Comment by 41hulk** [comment]
@GlenWeyl Kind review

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 19-Mar-24 18:31:08 UTC` by Gov4Git `dev`

#### Notice `hj2m3l`
This issue, managed as Gov4Git concern `39`, has been cancelled 🌂

The issue priority tally was `10.000000`.

Refunds issued:
- User @glenweyl was refunded `100.000000` credits

Tally breakdown by user:
- User @glenweyl contributed `10.000000` votes
