### ISSUE TITLE
Issuing credits for work on citations

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#471]
Issue 100000 credits to @Omoaholo.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Saturday, 09-Mar-24 05:32:16 UTC` by Gov4Git `dev`

Could not issue `100000` credits to member @omoaholo. Reopen the issue to retry.

Because: `file does not exist`
