### ISSUE TITLE
Add account of Estonia as exemplar to The Lost Dao chapter

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#48]
While we devote much more time to the story of Taiwan, Estonia is a precedent and exemplar for Taiwan.  There is a place at the end of the chapter where this should be filled in, in a case study of about 1 page/2-3 paragraphs.  Ideally it should be tied to the history in the chapter, including to Henry George, given the heavy use of land taxes in Estonia, though primary focus should be on the role of technology.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Thursday, 29-Feb-24 22:54:27 UTC` by Gov4Git `dev`

#### Notice `nadi33`
Started managing this issue as Gov4Git concern `48` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `52avsk`
This issue's __priority score__ is now `0.000000`.
The __cost of priority__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `5efryh`
The set of eligible proposals claiming this issue is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 01-Mar-24 20:45:15 UTC` by Gov4Git `dev`

#### Notice `6bgble`
This issue's __priority score__ is now `250.000000`.
The __cost of priority__ is `62500.000000`.
The __projected bounty__ is now `500.000000`.

#### Notice `q5b3aa`
The set of eligible proposals claiming this issue is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Sunday, 10-Mar-24 21:21:21 UTC` by Gov4Git `dev`

#### Notice `ellk5y`
This issue, managed as Gov4Git proposal `48`, has been cancelled 🌂

The __priority score__ of the issue was `250.000000`.
The __cost of priority__ of the issue was `62500.000000`.

Refunds issued:
- User @glenweyl was refunded `62500.000000` credits

Tally breakdown by user:
- User @glenweyl contributed `250.000000` votes
