### ISSUE TITLE
Issuing credits to Wes

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#485]
Issue 15000 credits to @wesc.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Sunday, 10-Mar-24 02:17:00 UTC` by Gov4Git `dev`

Could not issue `15000` credits to member @wesc. Reopen the issue to retry.

Because: `file does not exist`
