### ISSUE TITLE
Issuing credits to Shaurya

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#547]
Issue 350000 credits to @shauddub.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 13-Mar-24 12:00:34 UTC` by Gov4Git `dev`

Could not issue `350000` credits to member @shauddub. Reopen the issue to retry.

Because: `file does not exist`
