### ISSUE TITLE
(forwarded) potential (and rather complicated) issue with naming

### ISSUE THREAD

**Issue by msparkles** [pluralitybook/plurality#56]
Forwarded from https://github.com/johnhadaway/plurality.net/issues/6, we didn't see that that wasn't the current repo.

---

"Plurality" is often referring to the collective experiences of DID and other unspecified conditions of "having multiple people in one head".

It's a [rather common term](https://morethanone.info/).

Is renaming possible? It's a rather currently-trending term and it's used to *specify something currently having lots of issues at being specified*. Imagine if you named a project "bisexual" (potentially meaning "the two sexes") before the idea of homosexuality was recognized and addressable.

*Plurality* is not a bad name at all, it's just that it's really mistimed, because people are **currently** trying to gain attention for plurality the condition.

**Comment by pluralitybook** [comment]
Hey @Mg138, thanks for bringing this to the community's attention.  Do you have a Twitter handle?  I think it would be best to collectively explore that issue there and I'd like to credit you.

**Comment by Mg138** [comment]
We have a Twitter account at [mei_sparkles_](https://twitter.com/mei_sparkles_) but we don't actually use it at all.

It would be best to credit us by linking to https://mouse.lgbt/

Discussions can occur there, however, and y'all are free to tag us and we'll keep an eye out.

**Comment by Mg138** [comment]
Alternatively, we're planning on having a Fediverse account again, be it on Akkoma, Mastodon or some third secret thing.

If you have a public account there, feel free to update us on this.

**Comment by pluralitybook** [comment]
@Mg138 I hope you and folks from the DID-Plurality community will participate in the conversation I opened on pol.is: https://pol.is/7fzjfkudae

**Comment by Mg138** [comment]
@pluralitybook Hey, we were trying to push our own statements on there, but trying to connect via Twitter gives this:
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
with the returned data being `polis_err_twitter_auth_041`

And we don't have a Facebook account at all.

Is it possible that someone relay our statements? We're still coming up with them:
(Strikethru'd ones are ones we consider redundant, if they seem fine you can still add them.)

`"Plurality" is having recognition problems as a largely misunderstood term that doesn't simply mean and isn't limited to DID.`

`The name for a book is easier to change than the term for a vaguely shaped minority.`

`The point of the new term is to be generic and to reduce confusion within plurality communities, the introduction of the book may break it.`

~~`The term "plurality" as in the book could overwrite the medical condition as it gains popularity.`~~

~~`The general public should be aware of the medical condition more than the book.`~~

~~`The general public wouldn't recognize either of them, as they're terms for niche communities.`~~

`The communities are separated enough that there wouldn't be confusion.`

`The terms refer to different enough things that there wouldn't be a problem.`

`We should instead include a disclaimer that links to some info about plurality the condition.`

(You're free to discard those if they're found to be duplicates, we're not sure how to view all of the statements at once and check if ours have already been stated.)

**Comment by pluralitybook** [comment]
Done!

**Comment by pluralitybook** [comment]
Nevermind...I am running into the same issue.  Not sure what's going on...

**Comment by pluralitybook** [comment]
The pol.is poll is now unlocked, so please engage!

**Comment by pluralitybook** [comment]
Thanks again for your help on this, I think some really interesting meaning is emerging from the conversation.  Let's give it over the weekend maybe and then try to draw some conclusions?

**Comment by Mg138** [comment]
Totally! We're seeing some interesting results from the new questions as well.
(Also, did we accidentally add dupes, we didn't realize our statements were already added because it didn't show us the new statements :sweat_smile:)

We'd wait a bit longer than just the weekend, but yeah!

Thanks for listening to us as well, we think it's meaningful that a collaborative community interacts with (outside) individuals in a healthy way :)

**Comment by pluralitybook** [comment]
Happy to wait as long as you like!Infinite diversity in infinite combinationshttps://www.RadicalxChange.org.On Aug 4, 2023, at 4:03 PM, Madeline Sparkles ***@***.***> wrote:﻿
Totally! We're seeing some interesting results from the new questions as well.
(Also, did we accidentally add dupes, we didn't realize our statements were already added because it didn't show us the new statements 😅)
We'd wait a bit longer than just the weekend, but yeah!
Thanks for listening to us as well, we think it's meaningful that a collaborative community interacts with (outside) individuals in a healthy way :)

**Comment by pluralitybook** [comment]
@Mg138 Do you want to wait longer or do you have some meaning you've now extracted we should pull out?

**Comment by Mg138** [comment]
Hmm.

This is some interesting but confusing result. It seems that the majority of the people think it's not a very big deal, some think that there's no problem at all/it helps the plural community and some think that there's a slight problem.

Group B has a slight disagreement on that "the plurality tech community has been using it for a long time"(S3), but the group mostly have no opinion.

There's a divide between group A and B on "the book is easier to change"(S5) and "the term is to be generic"(S6), but most people haven't voted yet.

Most people disagree that the confusion is deeply hurtful, which is very fair.

Group C's opinions don't seem to form a logical group, there's some contradictory opinion.

We suggest that we wait on others to vote on the new statements, and additionally tell people that there's now new statements. It seems that most people haven't voted on them yet, even if the ones who do seem to have a strong divide.

**Comment by Mg138** [comment]
It would seem that Group A is mostly "people who have no acknowledgement of plural people" and Group B is "people who at least somewhat do".

Group C seems to just be confused people.

It would seem that the minority thinks that there's at least a slight problem, while the majority thinks there's no problem at all.

From the current results, we suggest that y'all DO consider changing name. The majority seems to not understand the plural situation, and we shouldn't repeat the human mistake of inventing new words for minorities because it got ruined one way or another.

IF the majority seemed to agree on the plural situation and the fact that the introduction of the book *might* break the generic and newly-rising term, then it would mean that we have a lot more room to think and discuss, and it would lean a lot more on not changing.

But it seems that the majority simply thinks there is... no problem at all? Which is quite frank. With the newly added statements, it suggests that the majority doesn't quite understand why there would be any issue. Which, if you've seen any movies or articles about plural people, and have any people in your life that are plural, you'll know how mis/underrepresented we are.

Going back to the "bisexual" analogy, you'd need to imagine a time when homosexuality is rarely heard of. It's hard to imagine because we don't live in a world like that anymore, but you'd need to think about it that way.

**Comment by Mg138** [comment]
Think about the word 「同志」。

It'd rather be weird if, 50 years ago, there was a book titled that, while people were still secretive about being homosexual.

And it would make sense that the author change the title because if it catches on, it would most likely mean the meaning is polluted. We still use the word 同志 to this day. It sure is also a word that has no attachment to gay people, but we intuitively understand Why the word is like this and have it as almost the default, modern meaning unless there's context that would suggest the original meaning (as in, comrade).

And that's the point, the imagined book might just mean that this word wouldn't be used as much today. And we'd very likely settle on another word.

**Comment by Mg138** [comment]
「同志」 is a good analogy here because it's
- A generic word that originally means something completely different
- Born from the fact that people don't know about gay people

Both of these are just like plurality, in fact we already discarded an earlier term "multiplicity" because it's highly medical and was later used to segregate people based on if they have DID or not.

We wrote an essay... but still, we'd like to wait for people to vote to finally decide our own concrete suggestion, for now, this essay is just a perspective.

**Comment by pluralitybook** [comment]
@Mg138 thank you.  I agree we should consider changing the name.  That is why we started this discussion, to consider it.  As to making meaning from the existing conversation, I don't tend to interpret the opinion groups as uncaring or confused,.  I tend to interpret them as coming from different foci and perspectives.  The principle within our community is trying to find things that can achieve rough consensus across these conflicting perspectives.  I am happy to wait for the conversation to go on longer.  At some point, however, it will be important to interpret the conversation according to the above principles.  If you don't have experience interpreting pol.is results, I am happy to offer my own read or to recruit a neutral party with such experience if you prefer.

**Comment by Mg138** [comment]
We admit we're biased, we'd like a neutral third party with experience as well!

We got ahead of ourselves, of course, we're ranty, sorry about that.

If you'd like to offer your own read, that'd be great as well.

**Comment by pluralitybook** [comment]
I haven't gotten responses yet so I will take a pass.  There seems to be general agreement, across opinion groups, that there is not a severe conflict here.  Whether there is a conflict at all and whether a disclaimer is superior to a name change seems to be somewhat divisive.   My takeaway is that for now we should keep this issue in mind and find a way to address it, but there is no even rough consensus for an immediate move to change names.

**Comment by GlenWeyl** [comment]
I am closing this for now, but feel free to revive if you think necessary @msparkles.
