### ISSUE TITLE
Issue credits.

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#576]
Issue 1600 credits to @41hulk.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Thursday, 14-Mar-24 21:46:05 UTC` by Gov4Git `dev`

Could not issue `1600` credits to member @41hulk. Reopen the issue to retry.

Because: `file does not exist`
