### ISSUE TITLE
Issuing credits to Joshua

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#593]
Issue 10000 credits to @joshuay1.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Friday, 15-Mar-24 13:56:30 UTC` by Gov4Git `dev`

Could not issue `10000` credits to member @joshuay1. Reopen the issue to retry.

Because: `file does not exist`
