### ISSUE TITLE
Issuing credits to Jesse for audiobook

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#921]
Issue 500000 credits to @canudoa9.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 20-May-24 15:09:02 UTC` by Gov4Git `dev`

Could not issue `500000` credits to member @canudoa9. Reopen the issue to retry.

Because: `file does not exist`
