### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by DanielAbalde** [pluralitybook/plurality#929]
### Your public repo

https://github.com/danielabalde/gov4git-identity-public.git

### Your public branch

main

**Comment by GlenWeyl** [comment]
Have you contributed to the project yet?

**Comment by DanielAbalde** [comment]
No, I just tried to join from the Gov4Git app to test it after starting the book.

**Comment by GlenWeyl** [comment]
Oh, if you can post a proof of purchase on the book on social media and link here, I'll approve here and give you credit.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 29-May-24 03:42:10 UTC` by Gov4Git `dev`

@danielabalde was added to the community.

**Comment by DanielAbalde** [comment]
https://x.com/DGANFT/status/1796659483667538288?t=mhufKKps2iA0PEa8wl9ooA

**Comment by GlenWeyl** [comment]
Your application was automatically rejected because of a mistake in formatting.  Here are beginners instructions if that is helpful: https://github.com/pluralitybook/plurality/blob/main/docs/contributing/Beginners%20contribution%20guide.md
[https://opengraph.githubassets.com/772d02be3da0bd3e615a7bfcc4942c75755f45647f8209be2009fb2ed213adee/pluralitybook/plurality]<https://github.com/pluralitybook/plurality/blob/main/docs/contributing/Beginners%20contribution%20guide.md>
plurality/docs/contributing/Beginners contribution guide.md at main · pluralitybook/plurality<https://github.com/pluralitybook/plurality/blob/main/docs/contributing/Beginners%20contribution%20guide.md>
Root repository for ⿻數位 Plurality: The Future of Collaborative Technology and Democracy by E. Glen Weyl, Audrey Tang and the Plurality Community - pluralitybook/plurality
github.com




___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects


________________________________
